"""Add position col to product_image

Revision ID: 2ce8e720b3bf
Revises: 1eaaec4bc44f
Create Date: 2022-12-28 18:25:34.691802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ce8e720b3bf'
down_revision = '1eaaec4bc44f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.drop_column('position')

    # ### end Alembic commands ###
