"""Add phoneNumber and buildingNumber columns

Revision ID: 611c7d1bbc74
Revises: 27385e1b07ad
Create Date: 2022-12-31 20:37:23.787834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '611c7d1bbc74'
down_revision = '27385e1b07ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('building', sa.VARCHAR(length=1000), nullable=True))
        batch_op.add_column(
            sa.Column('phone', sa.VARCHAR(length=1000), nullable=False))
        batch_op.alter_column('state',
                              existing_type=sa.VARCHAR(length=1000),
                              nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.alter_column('state',
                              existing_type=sa.VARCHAR(length=1000),
                              nullable=False)
        batch_op.drop_column('phoneNumber')
        batch_op.drop_column('buildingNumber')

    # ### end Alembic commands ###
