"""Increase review char limit

Revision ID: a1cba900155c
Revises: 22c93019f642
Create Date: 2022-12-22 00:41:12.239265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1cba900155c'
down_revision = '22c93019f642'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('review',
               existing_type=sa.VARCHAR(length=840),
               type_=sa.VARCHAR(length=25000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('review',
               existing_type=sa.VARCHAR(length=25000),
               type_=sa.VARCHAR(length=840),
               existing_nullable=True)

    # ### end Alembic commands ###
